### ISSUE TITLE
"Please implement SetLocationPage ::_getLoginMessages()" displayed on setlocation page

### ISSUE THREAD

**Issue by Toub** [BeWelcome/rox#5]
On current production Web site, with Iceweasel 38.0.1 (firefox) or Chromium 43.0.2357.65 on Debian Testing, the following message appears in a textarea on the top of the page when I open the setlocation page:

```
Please implement
SetLocationPage
 ::_getLoginMessages()

or create a file
"/var/rox/deployment/www.bewelcome.org-4dea01b/htdocs/../build/members/templates/setlocation._getloginmessages.php"
```

**Comment by Toub** [comment]
![bug-bw](https://cloud.githubusercontent.com/assets/367762/8461392/7699f3dc-202c-11e5-8fb5-70004c1c9541.png)

**Comment by thisismeonmounteverest** [comment]
The getLoginMessages method was private instead of protected. Seems that that only affected the setlocation page, though.

Fixed on the server for now.

**Comment by Toub** [comment]
Great, looks good now. I guess we can close the issue.

**Comment by thisismeonmounteverest** [comment]
I'd keep it open till it is submitted to the repository.

**Comment by KKKas** [comment]
https://www.bewelcome.org/setlocation:

```
Please implement
SetLocationPage
::getSubmenuItems()

or create a file
"/var/www/www.bewelcome.org/build/members/templates/setlocation.getsubmenuitems.php"
```

![image](https://user-images.githubusercontent.com/60153/83177643-4a670d80-a0d4-11ea-825a-8c912ebba505.png)

**Comment by crumbking** [comment]
Still an issue on live site. Please test on [beta.bewelcome.org](beta.bewelcome.org).

**Comment by crumbking** [comment]
Seems to work on www.bewelcome.org
@KKKas In case it's still an issue for you feel free to reopen.
